---
#
# Installing Java 8
#
# Add the Java ppa repository
- name: Add Java repository
 apt_repository:
   repo: ppa:webupd8team/java
# Automatically accepts the Oracle License popup in the terminal
- name: Automatically select the Oracle License
 shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
# Install Java 8
- name: Install the Java 8 package
 apt:
   name: oracle-java8-installer
   state: present
   update_cache: yes
